<?php
	$TEMBOO_USERNAME ='YOUR USERNAME';
	$TEMBOO_APP_NAME = 'TEMBOO APP NAME HERE';
	$TEMBOO_APP_KEY = 'TEMBOO APP KEY';
	
	$TWILIO_AUTH_TOKEN = 'ENTER YOUR TWILIO AUTH TOKEN';
	$TWILIO_ACCOUNT_SID = 'ENTER YOUR TWILIO ACCOUNT SID';
	$TWILIO_PHONE_NUMBER = 'ENTER THE PHONE NUMBER YOU ARE SENDING FROM';

	$GOOGLE_API_KEY = 'ENTER YOUR GOOGLE API KEY HERE';
?>